/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocIdRouteImport } from './routes/$docId'
import { Route as IndexRouteImport } from './routes/index'

const DocIdRoute = DocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$docId': typeof DocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$docId': typeof DocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$docId': typeof DocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$docId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$docId'
  id: '__root__' | '/' | '/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocIdRoute: typeof DocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$docId': {
      id: '/$docId'
      path: '/$docId'
      fullPath: '/$docId'
      preLoaderRoute: typeof DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocIdRoute: DocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
